### ISSUE TITLE
No longer works on Joomla 3.6.5

### ISSUE THREAD

**Issue by Simon-Davies** [WebuddhaInc/Joomla-cli-autoupdate#1]
This script no longer works on Joomla 3.6.5. Is anyone able to update it?

I have tried to run it with a cron job just as I do the Akeeba Backup CLI script.

Command used:

/usr/php/54/usr/bin/php /home1/***/public_html/cli/update.php --extensions >/dev/null 2>&1

Joomla really needs automatic updates as an opt in feature.

**Comment by dakuzen** [comment]
Simon - we raised several issues with the Joomla community about their direction with the update handler, of which they had no interest.  Their isolation of Joomla updates into the mishmash Akeeba code they deployed broke this cli script.  Rather than try to include their new Akeeba approach, which is likely to change again, we've implemented a custom handler into this script.

You should now be good to go.  Let me know if it doesn't work.
